// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAONArWJb-O8-IH2B191bg1mZ2QlGYmKRw',
    appId: '1:172007348276:android:9f6bdfa4a482bf0a291261',
    messagingSenderId: '172007348276',
    projectId: 'zemenaygozo-dfttla',
    databaseURL: 'https://zemenaygozo-dfttla-default-rtdb.firebaseio.com',
    storageBucket: 'zemenaygozo-dfttla.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx18y27hLqrFaLNh3sO0trlOO_WvdBeUE',
    appId: '1:172007348276:ios:cdde39b01ca72f26291261',
    messagingSenderId: '172007348276',
    projectId: 'zemenaygozo-dfttla',
    databaseURL: 'https://zemenaygozo-dfttla-default-rtdb.firebaseio.com',
    storageBucket: 'zemenaygozo-dfttla.firebasestorage.app',
    iosBundleId: 'com.sidama.sidamaWayGo',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA742H76-tYVsUyNBldKw3jYfWSAjB4aSM',
    appId: '1:172007348276:web:691ff4605db6656b291261',
    messagingSenderId: '172007348276',
    projectId: 'zemenaygozo-dfttla',
    authDomain: 'zemenaygozo-dfttla.firebaseapp.com',
    databaseURL: 'https://zemenaygozo-dfttla-default-rtdb.firebaseio.com',
    storageBucket: 'zemenaygozo-dfttla.firebasestorage.app',
    measurementId: 'G-QWFZZHHPWR',
  );
}
