class AppStrings {
  static const Map<String, Map<String, String>> strings = {
    'en': {
      'home': 'Home', 'bus': 'Bus', 'food': 'Food', 'tourist': 'Tourist',
      'profile': 'Profile', 'book_ride': 'Book Ride', 'bus_terminal': 'Bus Terminal',
      'city_taxi': 'City Taxi', 'taxi_queue': 'Taxi Queue', 'emergency': 'Emergency',
      'eco_shine': 'Eco-Shine', 'wallet': 'Wallet', 'admin': 'Admin',
      'hello': 'Hello', 'where_to_go': 'Where would you like to go today?',
      'services': 'Services', 'ai_assistant': 'AI Assistant',
      'select_language': 'Select Language', 'settings': 'Settings',
      'transit': 'Transit', 'explore': 'Explore', 'ai_chat': 'AI Chat',
      'city_map': 'City Map', 'intercity_bus': 'Intercity Bus', 'tourist_guide': 'Tourist Guide',
      'healthcare': 'Healthcare', 'pharmacy': 'Pharmacy', 'delivery': 'Delivery',
      'city_services': 'City Services', 'announcements': 'Announcements',
      'service_update': 'Service Update', 'bus_update_msg': 'New routes added to the New Terminal.',
      'health_notice': 'Health Notice', 'vaccine_drive_msg': 'Vaccination drive starting Monday.',
      'welcome_msg': 'Hawassa Smart City Mobility',
      'super_admin_title': 'Hawassa City OS',
      'predictive_insight': 'AI Predictive Insight',
      'app_title': 'SIDAMA WAY GO',
      'platform_name': 'SIDAMA WAY GO – Smart City Digital Platform',
      'tagline': 'Transportation • Tourism • Healthcare • Emergency • Smart Governance',
      'trip_history': 'Trip History',
      'payment': 'Payment',
      'notifications': 'Notifications',
      'language': 'Language',
      'help_support': 'Help & Support',
      'sign_out': 'Sign Out',
      'trips': 'Trips',
      'rating': 'Rating',
    },
    'am': {
      'home': 'መነሻ', 'bus': 'አውቶቡስ', 'food': 'ምግብ', 'tourist': 'ቱሪስት',
      'profile': 'መገለጫ', 'book_ride': 'ጉዞ ይያዙ', 'bus_terminal': 'አውቶቡስ ተርሚናል',
      'city_taxi': 'የከተማ ታክሲ', 'taxi_queue': 'ታክሲ ወረፋ', 'emergency': 'ድንገተኛ',
      'eco_shine': 'ኢኮ-ሻይን', 'wallet': 'ቦርሳ', 'admin': 'አስተዳዳሪ',
      'hello': 'ሰላም', 'where_to_go': 'ዛሬ የት መሄድ ይፈልጋሉ?',
      'services': 'አገልግሎቶች', 'ai_assistant': 'AI ረዳት',
      'select_language': 'ቋንቋ ይምረጡ', 'settings': 'ቅንብሮች',
      'transit': 'ትራንዚት', 'explore': 'አስስ', 'ai_chat': 'AI ውይይት',
      'city_map': 'የከተማ ካርታ', 'intercity_bus': 'የከተማ መካከለኛ አውቶቡስ', 'tourist_guide': 'የቱሪስት መመሪያ',
      'healthcare': 'ጤና ጥበቃ', 'pharmacy': 'ፋርማሲ', 'delivery': 'ማድረሻ',
      'city_services': 'የከተማ አገልግሎቶች', 'announcements': 'ማስታወቂያዎች',
      'service_update': 'የአገልግሎት ዝመና', 'bus_update_msg': 'አዳዲስ የአውቶቡስ መስመሮች ተጨምረዋል።',
      'health_notice': 'የጤና ማሳሰቢያ', 'vaccine_drive_msg': 'የክትባት ዘመቻ ሰኞ ይጀምራል።',
      'welcome_msg': 'የሀዋሳ ስማርት ከተማ እንቅስቃሴ',
      'super_admin_title': 'ሀዋሳ ከተማ OS',
      'predictive_insight': 'AI የመተንበይ ግንዛቤ',
      'app_title': 'ሲዳማ ዌይ ጎ',
      'platform_name': 'ሲዳማ ዌይ ጎ – ስማርት ሲቲ ዲጂታል ፕላትፎርም',
      'tagline': 'ትራንስፖርት • ቱሪዝም • ጤና ጥበቃ • ድንገተኛ አደጋ • ስማርት አስተዳደር',
      'trip_history': 'የጉዞ ታሪክ',
      'payment': 'ክፍያ',
      'notifications': 'ማሳወቂያዎች',
      'language': 'ቋንቋ',
      'help_support': 'እርዳታ እና ድጋፍ',
      'sign_out': 'ውጣ',
      'trips': 'ጉዞዎች',
      'rating': 'ደረጃ',
    },
    'sid': {
      'home': 'Mine', 'bus': 'Otoobusi', 'food': 'Sokka', 'tourist': 'Tuuristi',
      'profile': 'Ramme', 'book_ride': 'Adeezha Doora', 'bus_terminal': 'Otoobusi Terminaale',
      'city_taxi': 'Katama Taaksii', 'taxi_queue': 'Taaksii Saafalcho', 'emergency': 'Dawicho',
      'eco_shine': 'Eco-Shine', 'wallet': 'Boorsa', 'admin': 'Anga\'amaancho',
      'hello': 'Hawaadu', 'where_to_go': 'Hannara hara hawita?',
      'services': 'Soqansiwa', 'ai_assistant': 'AI Aanancho',
      'select_language': 'Afoo Doori', 'settings': 'Hajajaano',
      'transit': 'Transit', 'explore': 'Ha\'risi', 'ai_chat': 'AI Chat',
      'city_map': 'Map', 'intercity_bus': 'Intercity Bus', 'tourist_guide': 'Tourist Guide',
      'healthcare': 'Healthcare', 'pharmacy': 'Pharmacy', 'delivery': 'Delivery',
      'city_services': 'Services', 'announcements': 'Announcements',
      'service_update': 'Update', 'bus_update_msg': 'New bus routes.',
      'health_notice': 'Health', 'vaccine_drive_msg': 'Vaccine on Monday.',
      'welcome_msg': 'Hawaasa Smart City',
      'super_admin_title': 'Hawaasa OS',
      'predictive_insight': 'AI Predictive Insight',
      'app_title': 'SIDAMA WAY GO',
      'platform_name': 'SIDAMA WAY GO – Smart City Digital Platform',
      'tagline': 'Transportation • Tourism • Healthcare • Emergency • Smart Governance',
      'trip_history': 'Trip History',
      'payment': 'Payment',
      'notifications': 'Notifications',
      'language': 'Language',
      'help_support': 'Help & Support',
      'sign_out': 'Sign Out',
      'trips': 'Trips',
      'rating': 'Rating',
    },
  };
}
